
# docker-compose.yml
version: '3'
services:
  activemq:
    image: symptoma/activemq:5.17.3
    ports:
      - "61616:61616"
      - "8161:8161"
    environment:
      ACTIVEMQ_ADMIN_LOGIN: admin
      ACTIVEMQ_ADMIN_PASSWORD: admin

