spring.application.name=user-api-mongodb-english
server.port=8080
#MongoDB
spring.data.mongodb.uri=mongodb://localhost:27017/local
spring.data.mongodb.database=local

# JMS ActiveMQ (Embedded)
spring.activemq.broker-url=vm://0
# For external ActiveMQ, use: tcp://localhost:61616
# spring.activemq.user=admin
# spring.activemq.password=admin
user.updates.queue=user.updates.queue
