spring.application.name=user-api-mongodb-english
server.port=8080

# MongoDB (Embedded - Flapdoodle)
de.flapdoodle.mongodb.embedded.version=6.0.1
# spring.data.mongodb.uri=mongodb://localhost:27017/local
# spring.data.mongodb.database=local

# JMS ActiveMQ (Embedded Classic 6.x)
spring.activemq.broker-url=vm://localhost?broker.persistent=false
# For external ActiveMQ, use: tcp://localhost:61616
# spring.activemq.user=admin
# spring.activemq.password=admin
user.updates.queue=user.updates.queue
