name: Java CI with Maven

on:
  push:
    branches: [ "**" ] # Se ejecuta en todas las ramas al hacer push
  pull_request:
    branches: [ "main","demo" ] # Se ejecuta al abrir un PR hacia main y demo

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven
        
    - name: Build and Test with Maven
      run: mvn -B package --file pom.xml
